### ISSUE TITLE
Switch to  request with Accept: application/vnd.ipld.car

### ISSUE THREAD

**Issue by lidel** [olizilla/ipfs-get#12]
Just so we don't forget,  https://github.com/ipfs/go-ipfs/releases/tag/v0.13.0#support-for-block-and-car-response-formats makes below possible:

```console
$ curl  -H 'Accept: application/vnd.ipld.car' "http://127.0.0.1:8080/ipfs/bafybeiednzu62vskme5wpoj4bjjikeg3xovfpp4t7vxk5ty2jxdi4mv4bu" --output webui.car
$ ipfs dag import webui.car
```

**Comment by olizilla** [comment]
can i go for the `?format=car` query flavour instead?

**Comment by lidel** [comment]
Yes, both ways are part of [the spec](https://github.com/ipfs/specs/pull/283) and will work in go-ipfs 0.13+, I don't have a strong preference :)

My working argument for choosing header: it is less ambiguous to use explicit `Accept: application/vnd.ipld.car` in clients. Allows drive-by readers of your client code to google and find https://www.iana.org/assignments/media-types/application/vnd.ipld.car and learn about things that way.
